// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKUJyIo3-AqCQ2DpEGDkYuSoAO0uhrVY',
    appId: '1:532927467499:web:171eba50b14fdc10f093ae',
    messagingSenderId: '532927467499',
    projectId: 'notepad-f5010',
    authDomain: 'notepad-f5010.firebaseapp.com',
    storageBucket: 'notepad-f5010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Pj0KpKh-kr2YIEzwGm8-EEEO6ul8eCY',
    appId: '1:532927467499:android:cd8741214e892133f093ae',
    messagingSenderId: '532927467499',
    projectId: 'notepad-f5010',
    storageBucket: 'notepad-f5010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjm7M7ADZg3vuGnz5UAly_eNglox9Q-A',
    appId: '1:532927467499:ios:d92869f28360aa11f093ae',
    messagingSenderId: '532927467499',
    projectId: 'notepad-f5010',
    storageBucket: 'notepad-f5010.firebasestorage.app',
    iosBundleId: 'com.example.notepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjm7M7ADZg3vuGnz5UAly_eNglox9Q-A',
    appId: '1:532927467499:ios:d92869f28360aa11f093ae',
    messagingSenderId: '532927467499',
    projectId: 'notepad-f5010',
    storageBucket: 'notepad-f5010.firebasestorage.app',
    iosBundleId: 'com.example.notepad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKUJyIo3-AqCQ2DpEGDkYuSoAO0uhrVY',
    appId: '1:532927467499:web:25860c4deb6df915f093ae',
    messagingSenderId: '532927467499',
    projectId: 'notepad-f5010',
    authDomain: 'notepad-f5010.firebaseapp.com',
    storageBucket: 'notepad-f5010.firebasestorage.app',
  );
}
